version: "3.7"
services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    environment:
      - RTSP_PROTOCOLS=tcp
      - RTSP_USERNAME=${USERNAME}
      - RTSP_PASSWORD=${PASSWORD}
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    restart: always
    networks:
      - media-server

  stream-publisher:
    build:
      context: ../stream_publisher 
    image: stream-publisher
    container_name: stream-publisher
    depends_on:
      - rtsp-server
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ../stream_publisher:/app
      - ../videos:/videos  
    networks:
      - media-server
    command: ["python3", "main.py"]

networks:
  media-server:
    name: media-server
